// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package procexit

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type procexitProcExitEvent struct {
	_           structs.HostLayout
	TsNs        uint64
	StartTimeNs uint64
	Tgid        uint32
	ExitCode    uint32
	Comm        [16]int8
}

// loadProcexit returns the embedded CollectionSpec for procexit.
func loadProcexit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcexitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load procexit: %w", err)
	}

	return spec, err
}

// loadProcexitObjects loads procexit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*procexitObjects
//	*procexitPrograms
//	*procexitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcexitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcexit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// procexitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procexitSpecs struct {
	procexitProgramSpecs
	procexitMapSpecs
	procexitVariableSpecs
}

// procexitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procexitProgramSpecs struct {
	HandleProcExit *ebpf.ProgramSpec `ebpf:"handle_proc_exit"`
}

// procexitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procexitMapSpecs struct {
	ProcExitEvents *ebpf.MapSpec `ebpf:"proc_exit_events"`
	ProcExitHeap   *ebpf.MapSpec `ebpf:"proc_exit_heap"`
}

// procexitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procexitVariableSpecs struct {
}

// procexitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcexitObjects or ebpf.CollectionSpec.LoadAndAssign.
type procexitObjects struct {
	procexitPrograms
	procexitMaps
	procexitVariables
}

func (o *procexitObjects) Close() error {
	return _ProcexitClose(
		&o.procexitPrograms,
		&o.procexitMaps,
	)
}

// procexitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcexitObjects or ebpf.CollectionSpec.LoadAndAssign.
type procexitMaps struct {
	ProcExitEvents *ebpf.Map `ebpf:"proc_exit_events"`
	ProcExitHeap   *ebpf.Map `ebpf:"proc_exit_heap"`
}

func (m *procexitMaps) Close() error {
	return _ProcexitClose(
		m.ProcExitEvents,
		m.ProcExitHeap,
	)
}

// procexitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcexitObjects or ebpf.CollectionSpec.LoadAndAssign.
type procexitVariables struct {
}

// procexitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcexitObjects or ebpf.CollectionSpec.LoadAndAssign.
type procexitPrograms struct {
	HandleProcExit *ebpf.Program `ebpf:"handle_proc_exit"`
}

func (p *procexitPrograms) Close() error {
	return _ProcexitClose(
		p.HandleProcExit,
	)
}

func _ProcexitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed procexit_bpfel.o
var _ProcexitBytes []byte
