// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package pidruntime

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pidruntimeCpuAcct struct {
	_           structs.HostLayout
	LastStartNs uint64
	RuntimeNs   uint64
}

// loadPidruntime returns the embedded CollectionSpec for pidruntime.
func loadPidruntime() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PidruntimeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pidruntime: %w", err)
	}

	return spec, err
}

// loadPidruntimeObjects loads pidruntime and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pidruntimeObjects
//	*pidruntimePrograms
//	*pidruntimeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPidruntimeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPidruntime()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pidruntimeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pidruntimeSpecs struct {
	pidruntimeProgramSpecs
	pidruntimeMapSpecs
	pidruntimeVariableSpecs
}

// pidruntimeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pidruntimeProgramSpecs struct {
	TraceSchedSwitch *ebpf.ProgramSpec `ebpf:"trace_sched_switch"`
}

// pidruntimeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pidruntimeMapSpecs struct {
	CpuAcctAnchor *ebpf.MapSpec `ebpf:"_cpu_acct_anchor"`
	CpuAcctByPid  *ebpf.MapSpec `ebpf:"cpu_acct_by_pid"`
}

// pidruntimeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pidruntimeVariableSpecs struct {
}

// pidruntimeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPidruntimeObjects or ebpf.CollectionSpec.LoadAndAssign.
type pidruntimeObjects struct {
	pidruntimePrograms
	pidruntimeMaps
	pidruntimeVariables
}

func (o *pidruntimeObjects) Close() error {
	return _PidruntimeClose(
		&o.pidruntimePrograms,
		&o.pidruntimeMaps,
	)
}

// pidruntimeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPidruntimeObjects or ebpf.CollectionSpec.LoadAndAssign.
type pidruntimeMaps struct {
	CpuAcctAnchor *ebpf.Map `ebpf:"_cpu_acct_anchor"`
	CpuAcctByPid  *ebpf.Map `ebpf:"cpu_acct_by_pid"`
}

func (m *pidruntimeMaps) Close() error {
	return _PidruntimeClose(
		m.CpuAcctAnchor,
		m.CpuAcctByPid,
	)
}

// pidruntimeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPidruntimeObjects or ebpf.CollectionSpec.LoadAndAssign.
type pidruntimeVariables struct {
}

// pidruntimePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPidruntimeObjects or ebpf.CollectionSpec.LoadAndAssign.
type pidruntimePrograms struct {
	TraceSchedSwitch *ebpf.Program `ebpf:"trace_sched_switch"`
}

func (p *pidruntimePrograms) Close() error {
	return _PidruntimeClose(
		p.TraceSchedSwitch,
	)
}

func _PidruntimeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pidruntime_bpfel.o
var _PidruntimeBytes []byte
