// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package syscalls

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type syscallsSyscallCounts struct {
	_             structs.HostLayout
	Total         uint64
	FileOpen      uint64
	FileClose     uint64
	FileRead      uint64
	FileWrite     uint64
	FileUnlink    uint64
	FileRename    uint64
	FilePerm      uint64
	NetSocket     uint64
	NetConnect    uint64
	NetBind       uint64
	NetListen     uint64
	NetAccept     uint64
	NetSend       uint64
	NetRecv       uint64
	ProcExec      uint64
	ProcFork      uint64
	ProcKill      uint64
	PrivEscalate  uint64
	EscapeAttempt uint64
	MemLayout     uint64
	Other         uint64
}

// loadSyscalls returns the embedded CollectionSpec for syscalls.
func loadSyscalls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load syscalls: %w", err)
	}

	return spec, err
}

// loadSyscallsObjects loads syscalls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*syscallsObjects
//	*syscallsPrograms
//	*syscallsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSyscallsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSyscalls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// syscallsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallsSpecs struct {
	syscallsProgramSpecs
	syscallsMapSpecs
	syscallsVariableSpecs
}

// syscallsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallsProgramSpecs struct {
	TraceSysEnter *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
}

// syscallsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallsMapSpecs struct {
	SyscallsAnchor *ebpf.MapSpec `ebpf:"_syscalls_anchor"`
	CgidMap        *ebpf.MapSpec `ebpf:"cgid_map"`
	SyscallsByCgid *ebpf.MapSpec `ebpf:"syscalls_by_cgid"`
}

// syscallsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallsVariableSpecs struct {
}

// syscallsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallsObjects struct {
	syscallsPrograms
	syscallsMaps
	syscallsVariables
}

func (o *syscallsObjects) Close() error {
	return _SyscallsClose(
		&o.syscallsPrograms,
		&o.syscallsMaps,
	)
}

// syscallsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallsMaps struct {
	SyscallsAnchor *ebpf.Map `ebpf:"_syscalls_anchor"`
	CgidMap        *ebpf.Map `ebpf:"cgid_map"`
	SyscallsByCgid *ebpf.Map `ebpf:"syscalls_by_cgid"`
}

func (m *syscallsMaps) Close() error {
	return _SyscallsClose(
		m.SyscallsAnchor,
		m.CgidMap,
		m.SyscallsByCgid,
	)
}

// syscallsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallsVariables struct {
}

// syscallsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallsPrograms struct {
	TraceSysEnter *ebpf.Program `ebpf:"trace_sys_enter"`
}

func (p *syscallsPrograms) Close() error {
	return _SyscallsClose(
		p.TraceSysEnter,
	)
}

func _SyscallsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalls_bpfeb.o
var _SyscallsBytes []byte
