// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tcpstats

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpstatsTcpStats struct {
	_           structs.HostLayout
	BytesTx     uint64
	BytesRx     uint64
	PktsTx      uint64
	PktsRx      uint64
	Retransmits uint64
}

// loadTcpstats returns the embedded CollectionSpec for tcpstats.
func loadTcpstats() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpstatsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpstats: %w", err)
	}

	return spec, err
}

// loadTcpstatsObjects loads tcpstats and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpstatsObjects
//	*tcpstatsPrograms
//	*tcpstatsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpstatsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpstats()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpstatsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstatsSpecs struct {
	tcpstatsProgramSpecs
	tcpstatsMapSpecs
	tcpstatsVariableSpecs
}

// tcpstatsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstatsProgramSpecs struct {
	KprobeTcpCleanupRbuf   *ebpf.ProgramSpec `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"kprobe_tcp_retransmit_skb"`
	KretprobeTcpSendmsg    *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_sendmsg"`
}

// tcpstatsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstatsMapSpecs struct {
	TcpStatsAnchor *ebpf.MapSpec `ebpf:"_tcp_stats_anchor"`
	TcpStatsByTgid *ebpf.MapSpec `ebpf:"tcp_stats_by_tgid"`
}

// tcpstatsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstatsVariableSpecs struct {
}

// tcpstatsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpstatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstatsObjects struct {
	tcpstatsPrograms
	tcpstatsMaps
	tcpstatsVariables
}

func (o *tcpstatsObjects) Close() error {
	return _TcpstatsClose(
		&o.tcpstatsPrograms,
		&o.tcpstatsMaps,
	)
}

// tcpstatsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpstatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstatsMaps struct {
	TcpStatsAnchor *ebpf.Map `ebpf:"_tcp_stats_anchor"`
	TcpStatsByTgid *ebpf.Map `ebpf:"tcp_stats_by_tgid"`
}

func (m *tcpstatsMaps) Close() error {
	return _TcpstatsClose(
		m.TcpStatsAnchor,
		m.TcpStatsByTgid,
	)
}

// tcpstatsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpstatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstatsVariables struct {
}

// tcpstatsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpstatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstatsPrograms struct {
	KprobeTcpCleanupRbuf   *ebpf.Program `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpRetransmitSkb *ebpf.Program `ebpf:"kprobe_tcp_retransmit_skb"`
	KretprobeTcpSendmsg    *ebpf.Program `ebpf:"kretprobe_tcp_sendmsg"`
}

func (p *tcpstatsPrograms) Close() error {
	return _TcpstatsClose(
		p.KprobeTcpCleanupRbuf,
		p.KprobeTcpRetransmitSkb,
		p.KretprobeTcpSendmsg,
	)
}

func _TcpstatsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpstats_bpfel.o
var _TcpstatsBytes []byte
